version: '3.8'
services:
  user-service:
    build: ./user-service
    container_name: usercontad
    ports:
      - "3000:3000"
  product-service:
    build: ./product-service
    container_name: productcontad
    ports:
      - "3001:3001"
  order-service:
    build: ./order-service
    container_name: ordercontad
    ports:
      - "3002:3002"
  gateway-service:
    build: ./gateway-service
    container_name: gatewaycontad
    ports:
      - "3003:3003"
    depends_on:
      - user-service
      - product-service
      - order-service
